---
"$schema": https://steeltoe.io/schema/latest/schema.json
Spring:
  boot:
    admin:
      client:
        url: http://localhost:9090
        metadata:
          user.name: actuatorUser
          user.password: actuatorPassword
  Cloud:
    Config:
      #Env: blue
      PollingInterval: "00:00:10"
Security:
  Oauth2:
    Client:
      ValidateCertificates: false
Logging:
  IncludeScopes: false
  LogLevel:
    Default: Information
    Microsoft.AspNetCore: Warning
    Microsoft.EntityFrameworkCore: Warning
    Microsoft.EntityFrameworkCore.Migrations: Information
    Steeltoe.Discovery: Information
    Articulate: Information
Management:
  Endpoints:
    Cloudfoundry:
      ValidateCertificates: false
      Exposure:
        Include:
          - "*"
    Actuator:
      Exposure:
        Include:
          - "*"
Eureka:
  Client:
    Validate_certificates: false
    ShouldRegisterWithEureka: true
    HealthMonitoredApps: ers-backend
    
Discovery:
  Services:
  - ServiceId: ers-blue
    Host: localhost
    Port: 5001
  - ServiceId: ers-green
    Host: localhost
    Port: 5000